sudo: required
language: node_js
node_js:
- '4.2.2'
before_install:
- npm install -g npm
before_script:
- npm install -g gulp
script:
- npm test 
- gulp coveralls
- gulp bump-patch
- gulp bump-minor
- gulp bump-major
