init:
  - git config --global core.autocrlf true
# What combinations to test
environment:
  matrix:
    - nodejs_version: "4.2.2"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install
  - npm install gulp -g
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584  
  - npm test
  - gulp bump-patch
  - gulp bump-minor
  - gulp bump-major  
after_test:
  - gulp coveralls